#!/bin/sh /etc/rc.common

USE_PROCD=1

START=95
STOP=01

start_service() {
    procd_open_instance
    procd_set_param command /mnt/sda1/nkn/nknd -p YOURPASSWORD --no-nat --config /mnt/sda1/nkn/config.json --wallet /mnt/sda1/nkn/wallet.json --log /mnt/sda1/nkn/Log --chaindb /mnt/sda1/nkn/ChainDB
    procd_append_param respawn 3600
    procd_append_param respawn 5
    procd_append_param respawn -1
    procd_close_instance
}